# Generated by Django 6.1.1 on 2026-09-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('options', models.TextField()),
                ('place', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
