# Generated by Django 6.1.1 on 2026-09-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='options',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='place',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
