# Generated by Django 6.1.1 on 2026-09-16 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_option_alter_subscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionToSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.option')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.subscription')),
            ],
        ),
    ]
