# Generated by Django 6.1.1 on 2026-09-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_optiontosubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='optiontosubscription',
            options={'verbose_name': 'Опция к подписке', 'verbose_name_plural': 'Опции к подпискам'},
        ),
    ]
